#!/usr/bin/env python3
"""Apply pinned Mia DFlash retention changes before any model is initialized.

v1.4: the contract names an explicit ``order`` (Mia's Dockerfile order:
hybrid prefix hit, per-group retention, mamba-align state free) and every
target is staged under its package-relative path with a minimal, fixed
environment, so the generated bytes do not depend on the caller's env.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

from _installer_guard import require_overrides


ENV = {
    'vllm/v1/core/kv_cache_coordinator.py': 'GLM53_KV_COORDINATOR_PY',
    'vllm/v1/core/block_pool.py': 'GLM53_BLOCK_POOL_PY',
    'vllm/v1/core/single_type_kv_cache_manager.py': 'GLM53_SINGLE_TYPE_KV_CACHE_MANAGER_PY',
    'vllm/v1/kv_cache_interface.py': 'GLM53_KV_CACHE_INTERFACE_PY',
}


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def generate(befores: dict[str, bytes], recipe: Path, order: list[str]) -> dict[str, bytes]:
    """Run the pinned patchers, in ``order``, over staged copies of ``befores``."""
    with tempfile.TemporaryDirectory(prefix='jspark3-swa-') as temporary:
        stage = Path(temporary)
        env = {'PATH': os.environ.get('PATH', '/usr/bin:/bin'), 'LC_ALL': 'C.UTF-8',
               'PYTHONDONTWRITEBYTECODE': '1'}
        for name, data in befores.items():
            staged = stage / name
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_bytes(data)
            env[ENV[name]] = str(staged)
        for name in order:
            try:
                require_overrides(recipe / 'overlays' / name, env)
            except ValueError as exc:
                raise RuntimeError(str(exc)) from None
            subprocess.run([sys.executable, '-S', str(recipe / 'overlays' / name)],
                           env=env, cwd=stage, check=True, stdout=subprocess.PIPE)
        return {name: (stage / name).read_bytes() for name in befores}


def apply(package_root: Path, recipe: Path) -> dict:
    contract = json.loads((recipe / 'config/swa-contract.json').read_text())
    order = contract['order']
    if sorted(order) != sorted(contract['patches']) or len(set(order)) != len(order):
        raise RuntimeError('SWA patch order does not name every pinned patch exactly once')
    if not set(contract['targets']) <= set(ENV):
        raise RuntimeError('SWA contract names a target without a staging override')
    targets = {name: package_root / name for name in contract['targets']}
    for name, path in targets.items():
        if path.is_symlink() or not path.is_file() or package_root.resolve() not in path.resolve().parents:
            raise RuntimeError(f'unsafe SWA target: {name}')
    for name, digest in contract['patches'].items():
        if sha(recipe / 'overlays' / name) != digest:
            raise RuntimeError(f'SWA patch source drift: {name}')
    observed = {name: sha(path) for name, path in targets.items()}
    before = {name: row['before'] for name, row in contract['targets'].items()}
    after = {name: row['after'] for name, row in contract['targets'].items()}
    if observed == after:
        state = 'ALREADY_APPLIED'
    elif observed == before:
        generated = generate({name: path.read_bytes() for name, path in targets.items()},
                             recipe, order)
        for name, path in targets.items():
            if hashlib.sha256(generated[name]).hexdigest() != after[name]:
                raise RuntimeError(f'SWA generated bytes drift: {name}')
            compile(generated[name], str(path), 'exec')
        # A partial replacement is never accepted: subsequent starts must
        # match the complete before or after set, and readiness follows receipt.
        for name, path in targets.items():
            with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
                handle.write(generated[name])
                handle.flush()
                os.fsync(handle.fileno())
                staged = Path(handle.name)
            staged.chmod(path.stat().st_mode & 0o777)
            os.replace(staged, path)
        state = 'APPLIED'
    else:
        raise RuntimeError('SWA target set is unknown, mixed, or corrupt')
    if {name: sha(path) for name, path in targets.items()} != after:
        raise RuntimeError('SWA final verification failed')
    return {'schema_version': 2, 'state': state, 'rank': os.environ.get('NODE_RANK'),
            'contract_sha256': sha(recipe / 'config/swa-contract.json'),
            'order': order, 'targets': after, 'ablit': int(os.environ['ABLIT'])}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--package-root', type=Path, required=True)
    parser.add_argument('--recipe-root', type=Path, required=True)
    parser.add_argument('--receipt', type=Path, required=True)
    args = parser.parse_args()
    try:
        receipt = apply(args.package_root, args.recipe_root)
        args.receipt.write_text(json.dumps(receipt, sort_keys=True) + '\n')
        print('JSPARK3_SWA_PASS ' + json.dumps(receipt, sort_keys=True))
        return 0
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f'REFUSE: {exc}', file=sys.stderr)
        return 9


if __name__ == '__main__':
    raise SystemExit(main())
